# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'run_gallery_tv_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(320, 60, 131, 51))
        self.pushButton_add_1 = QPushButton(self.centralwidget)
        self.pushButton_add_1.setObjectName(u"pushButton_add_1")
        self.pushButton_add_1.setGeometry(QRect(90, 160, 121, 51))
        self.pushButton_add_2 = QPushButton(self.centralwidget)
        self.pushButton_add_2.setObjectName(u"pushButton_add_2")
        self.pushButton_add_2.setGeometry(QRect(250, 160, 121, 51))
        self.pushButton_add_3 = QPushButton(self.centralwidget)
        self.pushButton_add_3.setObjectName(u"pushButton_add_3")
        self.pushButton_add_3.setGeometry(QRect(430, 160, 121, 51))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 30, 471, 21))
        self.pushButton_add_4 = QPushButton(self.centralwidget)
        self.pushButton_add_4.setObjectName(u"pushButton_add_4")
        self.pushButton_add_4.setGeometry(QRect(600, 160, 121, 51))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(120, 140, 71, 21))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 140, 71, 21))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(450, 140, 71, 21))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(590, 140, 71, 21))
        self.pushButton_del_1 = QPushButton(self.centralwidget)
        self.pushButton_del_1.setObjectName(u"pushButton_del_1")
        self.pushButton_del_1.setGeometry(QRect(90, 440, 121, 41))
        self.pushButton_del_2 = QPushButton(self.centralwidget)
        self.pushButton_del_2.setObjectName(u"pushButton_del_2")
        self.pushButton_del_2.setGeometry(QRect(250, 440, 121, 31))
        self.pushButton_del_3 = QPushButton(self.centralwidget)
        self.pushButton_del_3.setObjectName(u"pushButton_del_3")
        self.pushButton_del_3.setGeometry(QRect(410, 430, 121, 41))
        self.pushButton_del_4 = QPushButton(self.centralwidget)
        self.pushButton_del_4.setObjectName(u"pushButton_del_4")
        self.pushButton_del_4.setGeometry(QRect(570, 430, 121, 51))
        self.pushButton_play_1 = QPushButton(self.centralwidget)
        self.pushButton_play_1.setObjectName(u"pushButton_play_1")
        self.pushButton_play_1.setGeometry(QRect(90, 490, 121, 51))
        self.pushButton_play_2 = QPushButton(self.centralwidget)
        self.pushButton_play_2.setObjectName(u"pushButton_play_2")
        self.pushButton_play_2.setGeometry(QRect(250, 480, 121, 51))
        self.pushButton_play_2.setFlat(True)
        self.pushButton_play_3 = QPushButton(self.centralwidget)
        self.pushButton_play_3.setObjectName(u"pushButton_play_3")
        self.pushButton_play_3.setGeometry(QRect(410, 490, 121, 51))
        self.pushButton_play_4 = QPushButton(self.centralwidget)
        self.pushButton_play_4.setObjectName(u"pushButton_play_4")
        self.pushButton_play_4.setGeometry(QRect(570, 490, 121, 51))
        self.pushButton_up_1 = QPushButton(self.centralwidget)
        self.pushButton_up_1.setObjectName(u"pushButton_up_1")
        self.pushButton_up_1.setGeometry(QRect(180, 260, 51, 51))
        self.pushButton_dn_1 = QPushButton(self.centralwidget)
        self.pushButton_dn_1.setObjectName(u"pushButton_dn_1")
        self.pushButton_dn_1.setGeometry(QRect(180, 340, 51, 51))
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(470, 10, 231, 101))
        self.listWidget_1 = QListWidget(self.centralwidget)
        self.listWidget_1.setObjectName(u"listWidget_1")
        self.listWidget_1.setGeometry(QRect(60, 220, 111, 192))
        self.pushButton_dn_2 = QPushButton(self.centralwidget)
        self.pushButton_dn_2.setObjectName(u"pushButton_dn_2")
        self.pushButton_dn_2.setGeometry(QRect(370, 340, 51, 51))
        self.listWidget_2 = QListWidget(self.centralwidget)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(250, 220, 111, 192))
        self.pushButton_up_2 = QPushButton(self.centralwidget)
        self.pushButton_up_2.setObjectName(u"pushButton_up_2")
        self.pushButton_up_2.setGeometry(QRect(370, 260, 51, 51))
        self.pushButton_up_3 = QPushButton(self.centralwidget)
        self.pushButton_up_3.setObjectName(u"pushButton_up_3")
        self.pushButton_up_3.setGeometry(QRect(550, 260, 51, 51))
        self.pushButton_dn_3 = QPushButton(self.centralwidget)
        self.pushButton_dn_3.setObjectName(u"pushButton_dn_3")
        self.pushButton_dn_3.setGeometry(QRect(550, 340, 51, 51))
        self.listWidget_3 = QListWidget(self.centralwidget)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(430, 220, 111, 192))
        self.pushButton_dn_4 = QPushButton(self.centralwidget)
        self.pushButton_dn_4.setObjectName(u"pushButton_dn_4")
        self.pushButton_dn_4.setGeometry(QRect(730, 340, 51, 51))
        self.pushButton_up_4 = QPushButton(self.centralwidget)
        self.pushButton_up_4.setObjectName(u"pushButton_up_4")
        self.pushButton_up_4.setGeometry(QRect(730, 260, 51, 51))
        self.listWidget_4 = QListWidget(self.centralwidget)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(610, 220, 111, 192))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(680, 560, 91, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_play_1.raise_()
        self.pushButton.raise_()
        self.pushButton_add_1.raise_()
        self.pushButton_add_2.raise_()
        self.pushButton_add_3.raise_()
        self.label.raise_()
        self.pushButton_add_4.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.pushButton_del_1.raise_()
        self.pushButton_del_2.raise_()
        self.pushButton_del_3.raise_()
        self.pushButton_del_4.raise_()
        self.pushButton_play_2.raise_()
        self.pushButton_play_3.raise_()
        self.pushButton_play_4.raise_()
        self.pushButton_up_1.raise_()
        self.pushButton_dn_1.raise_()
        self.listWidget.raise_()
        self.listWidget_1.raise_()
        self.pushButton_dn_2.raise_()
        self.listWidget_2.raise_()
        self.pushButton_up_2.raise_()
        self.pushButton_up_3.raise_()
        self.pushButton_dn_3.raise_()
        self.listWidget_3.raise_()
        self.pushButton_dn_4.raise_()
        self.pushButton_up_4.raise_()
        self.listWidget_4.raise_()
        self.label_2.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Change Directory", None))
        self.pushButton_add_1.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.pushButton_add_2.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.pushButton_add_3.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"C:\\video", None))
        self.pushButton_add_4.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Customer", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Vendor", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"General", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Partner", None))
        self.pushButton_del_1.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButton_del_2.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButton_del_3.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButton_del_4.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButton_play_1.setText(QCoreApplication.translate("MainWindow", u"Play (Customer)", None))
        self.pushButton_play_2.setText(QCoreApplication.translate("MainWindow", u"Play (Vendor)", None))
        self.pushButton_play_3.setText(QCoreApplication.translate("MainWindow", u"Play (General)", None))
        self.pushButton_play_4.setText(QCoreApplication.translate("MainWindow", u"Play (Partner)", None))
        self.pushButton_up_1.setText(QCoreApplication.translate("MainWindow", u"up", None))
        self.pushButton_dn_1.setText(QCoreApplication.translate("MainWindow", u"down", None))
        self.pushButton_dn_2.setText(QCoreApplication.translate("MainWindow", u"down", None))
        self.pushButton_up_2.setText(QCoreApplication.translate("MainWindow", u"up", None))
        self.pushButton_up_3.setText(QCoreApplication.translate("MainWindow", u"up", None))
        self.pushButton_dn_3.setText(QCoreApplication.translate("MainWindow", u"down", None))
        self.pushButton_dn_4.setText(QCoreApplication.translate("MainWindow", u"down", None))
        self.pushButton_up_4.setText(QCoreApplication.translate("MainWindow", u"up", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Ke\u5b78\u4e4b\u7236@2025", None))
    # retranslateUi

